name: Main

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  build_test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install nightly Rust and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: rustfmt

      - name: Build
        run: cargo build

      - name: Build Examples
        run: cargo build --examples

      - name: Test
        run: cargo test

      - name: Check Fmt
        run: cargo fmt --all -- --check
